name: Dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write
  checks: read
  actions: read
  statuses: read

jobs:
  automerge:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: fastify/github-action-merge-dependabot@v3