name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - "dev/**"
    paths-ignore:
      - "README.md"
      - "LICENSE*"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    uses: T2PeNBiX99wcoxKv3A4g/Release-Workflows/.github/workflows/jvm_release.yml@main
    with:
      prerelease: true