name: Release

on:
  push:
    branches:
      - 1.21.5

jobs:
  build:
    name: Ubuntu Latest Build
    permissions:
      contents: write
    strategy:
      matrix:
        # Use these Java versions
        java: [
          23,    # Current Java LTS
        ]
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
      new_version: ${{ steps.change_version.outputs.new_version }}
      changelog: ${{ steps.git-cliff2.outputs.content }}
    steps:
      - name: Check-out repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'oracle'

      - name: Pull changes
        run: git pull

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pre_release_branches: "fast"

      - name: Clone `CSharp-Workflow-Scripts` Python script
        run: git clone https://github.com/T2PeNBiX99wcoxKv3A4g/CSharp-Workflow-Scripts.git .scripts

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '>=3.14'
          cache: 'pip'

      - name: Install Dependencies
        run: pip install -r .scripts/requirements.txt

      - name: Change version in `gradle.properties`
        id: change_version
        run: python .scripts/change_version.py change-version ./gradle.properties mod_version ${{ steps.tag_version.outputs.new_tag }}

      - name: Remove `.scripts`
        run: rm -rf .scripts

      - name: Install `typos-cli` from `crates.io`
        uses: baptiste0928/cargo-install@v3
        with:
          crate: typos-cli

      - name: Pull changes
        run: git pull

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          args: --verbose --config-url https://raw.githubusercontent.com/T2PeNBiX99wcoxKv3A4g/Git-Cliff-Template/refs/heads/master/cliff.toml
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Set git user
        uses: fregante/setup-git-user@v2

      - name: Check for changes
        run: git status

      - name: Stage changed files
        run: git add .

      - name: Commit changed files
        run: "git commit -m 'Action: Update version in `gradle.properties`'"

      - name: Fetch from 1.21.5
        run: git fetch origin 1.21.5

      - name: Push code to 1.21.5
        run: git push origin 1.21.5

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build

      - name: Pull changes
        run: git pull

      - name: Generate a release body
        uses: orhun/git-cliff-action@v4
        id: git-cliff2
        with:
          args: --verbose --latest --strip header --config-url https://raw.githubusercontent.com/T2PeNBiX99wcoxKv3A4g/Git-Cliff-Template/refs/heads/master/cliff.toml
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          OUTPUT: CHANGES.md
          GITHUB_REPO: ${{ github.repository }}

      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
  
  upload:
    name: Create Release
    permissions:
      contents: write
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v5
        with:
          path: release
          merge-multiple: true

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release/*.jar"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.build.outputs.new_tag }}
          name: Release 1.21.5 ${{ needs.build.outputs.new_tag }}
          body: ${{ needs.build.outputs.changelog }}